---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/backgrounds":
    get:
      summary: get background photo
      tags:
      - Backgrounds
      description: Retreives a background photo from Flickr
      parameters:
      - name: location
        in: query
        required: true
        description: city, state
        schema:
          type: string
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3001
